# This file is generated by cloud-config upon instance first bootup
# it might be changed by puppet later

[general]
state_file = /var/awslogs/state/agent-state

[/var/log/ecs/init]
file = /var/log/ecs/ecs-init.log
log_group_name = ${ ecs_init_log_group }
log_stream_name = {instance_id}
datetime_format = %Y-%m-%dT%H:%M:%SZ

[/var/log/ecs/audit]
file = /var/log/ecs/audit.log.*
log_group_name = ${ ecs_audit_log_group }
log_stream_name = {instance_id}
datetime_format = %Y-%m-%dT%H:%M:%SZ

[/var/log/ecs/ecs-agent.log]
file = /var/log/ecs/ecs-agent.log.*
log_group_name = ${ ecs_agent_log_group }
log_stream_name = {instance_id}
datetime_format = %Y-%m-%dT%H:%M:%SZ
